### ISSUE TITLE
Stylistic suggestion: macros to shorten standard error handling patterns

### ISSUE THREAD

**Issue by LoupVaillant** [ewd340/kr#4]
I noticed a couple recurring patterns:

```C
if (!condition) {
    BAIL(ERROR_CODE);
}
```

With a little macro those 3 lines could be reduced to just one:

```C
#define CHECK(condition, ERROR_CODE) do { \
        if (!condition) {                 \
            BAIL(ERROR_CODE);             \
        }                                 \
    } while (0)

// ...

CHECK(condition, ERROR_CODE);
```

You could stop there. But I noticed another, quite frequent sub-pattern:

```C
err = function(arg1, arg2, arg3);
if (err != ERR_OK) {
    BAIL(err);
}
```

This one could also be reduced to a single line. (Gcc and Clang support having zero optional argument, but they may complain about it not being standard).

```C
#define CHECKED_CALL(function, ...) do { \
        err = function(__VA_ARGS__);     \
        if (err != ERR_OK) {             \
            BAIL(err);                   \
        }                                \
    } while (0)

// ...

CHECKED_CALL(function, arg1, arg2, arg3);
CHECKED_CALL(function2); // zero optional arguments is not standard unfortunately
```

Or you can avoid `__VA_ARGS__` altogether by wrapping the function call itself:

```C
#define CHECKED_EXPR(expr) do { \
        err = expr;             \
        if (err != ERR_OK) {    \
            BAIL(err);          \
        }                       \
    } while (0)

// ...

CHECKED_EXPR(function(arg1, arg2, arg3));
CHECKED_EXPR(function2()); // perfectly standard !
```

Now many would say this is too many macros. Or the macros are too heavy, or it's unmaintainable because they're macros… Perhaps. It's a balance between compactness and approachability. My guess here is that those macros are worth the trouble, because they are part of a consistent error handling system that pervades the whole program. The patterns they replace are everywhere, so the 30 seconds spent on understanding them are quickly saved when reading the rest of the program.

And compactness in my opinion doesn't just make the code shorter, it makes it more readable: less error handling noise, more business logic, and with shorter function there's a greater chance that the exit point is visible in the same screen as the `BAIL()` call.

Now that's the kind of thing that should be tested, see if it suits your taste. I've tested this on other projects and it certainly suits mine. :smile:

**Comment by ewd340** [comment]
Glad to see that I'm not alone in thinking this way. In fact, I have considered the same situation in a slightly different (but most similar) fashion. I have implemented it successfully in a branch but hated that some applications of these macros gave me lines longer that 80 characters in my code, but also because, as you said, I thought that maybe it's too many macros to digest. But your point stands.

In my approach, I went for more _active_ verbs. Instead of _checking_. That is, I would still _bail_ but conditionally.  For instance:

for a pattern such as:
```c
if (condition) {
    BAIL(ERROR_CODE);
}
```

I would do:
```c
#define BAIL_IF(condition, ERROR_CODE) do { \
        if (condition) {                 \
            BAIL(ERROR_CODE);             \
        }                                 \
    } while (0)

//...

BAIL_IF(fillrand(key, KEY_SIZE), ERR_RANDOM);    // fillrand returns 0 on success.
```


And similarly, when testing against `ERR_OK`, I would do:

```c
#define BAIL_IF_NOT_OK(exp) do { \
        enum error ERROR_CODE = (exp);
        if (ERROR_CODE  != ERR_OK) {                 \
            BAIL(ERROR_CODE);             \
        }                                 \
    } while (0)

//...

BAIL_IF_NOT_OK(write_keyfile(out, key));
```
Indeed,  it gives us a more compact code but also a more expressive and a less-prone-to-mistakes coding style. Now, the question still persists: _how much is too much_ macros? :-)

**Comment by LoupVaillant** [comment]
> Now, the question still persists: _how much is too much_ macros? :-)

My personal heuristic is that if a macro like these ones are called more than 10 times, they're generally worth it.

---

Now I do need to amend my initial proposal: I like your `BAIL_IF` and `BAIL_IF_NOT_OK` macros, but I realise the latter saves less than the former. Consider this code:

```C
if (condition) {
    BAIL(ERROR_CODE);
}
err = function(arg1, arg2, arg3);
if (err != ERR_OK) {
    BAIL(err);
}
```

With just `BAIL_IF()`, we reduce it down to:

```C
BAIL_IF(condition, ERROR_CODE);
err = function(arg1, arg2, arg3);
BAIL_IF(err != ERR_OK, err);
```

And if by any chance `ERR_OK` equals zero (and I think it [does](https://github.com/ewd340/kr/blob/master/src/kr.c#L83-L84), though you could write `ERR_OK = 0` to make sure of that), we could even simplify a bit further:

```C
BAIL_IF(condition, ERROR_CODE);
err = function(arg1, arg2, arg3);
BAIL_IF(err, err);
```

Compare with:

```C
BAIL_IF(condition, ERROR_CODE);
BAIL_IF_NOT_OK(function(arg1, arg2, arg3));
```

Now `BAIL_IF_NOT_OK()` doesn't look like it saves that much code after all. On the other hand its definition can be seriously simplified (no `do {} while (0)` trick because this time we can just omit the semicolon at the end):

```C
#define BAIL_IF_NOT_OK(exp) \
    err = (exp);            \
    BAIL_IF(err, err)
```

I kinda hate the free `err` variable, though, especially since `BAIL()` (and therefore `BAIL_IF()`) already sets it. But I don't see any other alternative than declaring a local variable in a `do {} while (0)` contraption again, which would be worse. This little complication would made me hesitate to use this macro if it ends up being called less than 10 times.

---

One last suggestion: perhaps try not to use the `BAIL()` macro to exit normally. It's a bit counter-intuitive, and stumped me for half a second when I first saw it. My personal preference (and I'm being _real_ nitpicky there) would call for the following changes:

- Rename all `bail` labels into `cleanup` instead. Because that's literally what they do, regardless of exit type.
- Make sure the `err` variable is always initialised with ERR_OK (they already are).
- Replace all `BAIL(ERR_OK)` calls (I spotted 6 of them) by `goto cleanup`.

_Or_, try to find a way not to ever write `BAIL(ERR_OK)`. Ideally the happy path should naturally fall all the way down the function body, and early exists should only come from error handling. The end game here would be code looking like this:

```C
// init code
do_stuff_1();
BAIL_IF(nope1, ERR_1);
do_stuff_2();
BAIL_IF(nope2, ERR_2);
do_stuff_3();
BAIL_IF(nope3, ERR_3);
bail:
    // cleanup code
    return err;
```

All nice and flat.

**Comment by chkoreff** [comment]
Well if you're coding to the JPL standard, which I'm starting to do, then "goto" is out of the question.  I know that's very strict, but in that case I'm either using "else if" or I'm setting an "err" code and checking it as a guard on subsequent conditions.

Or use this kind of thing (which ultimately is still a guard):

https://youtu.be/QpAhX-gsHMs?t=1392

**Comment by ewd340** [comment]
@LoupVaillant, we're getting very close to an ideal solution I feel.

See, I was about to tell you that we need to keep that `BAIL(ERR_OK)` to avoid having to deal with a complex nesting of if/elses, and that your last _flow_ wasn't always this obvious, but I checked the code, and we definitely can do without it.

Let us review some of its uses in the code:

- In `get_passphrase`


```c
if (config.confirm) {
    // If no protection is needed, do not ask for a confirmation.
    if ((mode == MODE_KEYEDIT) && (!passphrase[0])) {
        BAIL(ERR_OK);
    }
    uint8_t tmp[MAXPASS];
    int r1 = read_password(tmp, sizeof(tmp), config.prompt_repeat);
    if (r1 == 0) {
        BAIL(ERR_PASS_READ_FAIL);
    }
    if (r0 != r1 || memcmp(passphrase, tmp, r0)) {
        BAIL(ERR_PASS_NOT_MATCH);
    }
    crypto_wipe(tmp, sizeof(tmp));
}
```

could easily be refactored to avoid using it.

- In [read_key](https://github.com/ewd340/kr/blob/50396256904cffffd4e6a66037efe5301632de02/src/kr.c#L430), it is simply redundant since it's inside an `if` followed by an `else` which comes just before the cleaning point. So it can easily be removed altogether.

- in [main](https://github.com/ewd340/kr/blob/50396256904cffffd4e6a66037efe5301632de02/src/kr.c#L617-L622), while parsing arguments (especially for `-V` and `-h`). Since these two options just print the version and the usage text (resp.), we can delegate the exit to the functions `print_version(void)` and `print_usage(void)`. There's no cleaning to be done, right? Or could there be? The passphrase maybe? If the user insists on giving it on the command line.

- Same thing in [line 640](https://github.com/ewd340/kr/blob/50396256904cffffd4e6a66037efe5301632de02/src/kr.c#L640).

- The obvious one, on [line 755](https://github.com/ewd340/kr/blob/50396256904cffffd4e6a66037efe5301632de02/src/kr.c#L755). We're about to exit the switch statement anyways and go to the cleaning label.

**Conclusion**: we don't need `BAIL(ER_OK)`.

Also, I fully agree with you on the `BAIL_IF_NOT_OK` macro.

Now, the `BAIL_IF(err, err)` construct, I actually have done it while playing with this idea, and find it kind of obscure (magical). Sure, in that `enum error` type,  `ERR_OK == 0`, but the code's reader will have to mentally parse it (even if he/she read the macro definition before).

To think about it: all our `BAIL`s follow a test actually. _But_! I would definitely prefer to write something like this:

```c
if (r0 != r1 || memcmp(passphrase, tmp, r0)) {
    BAIL(ERR_PASS_NOT_MATCH);
}

```

Instead of something like:

```c
BAIL_IF((r0 != r1 || memcmp(passphrase, tmp, r0)), ERR_PASS_NOT_MATCH)

```

Don't you think?

All in all, I think it would be nice to have both `BAIL` and `BAIL_IF` and they won't be used for `ERR_OK` since we don't need to anyways.

**Comment by ewd340** [comment]
@chkoreff Thanks for the link, I'll give it a watch :)

I actually don't follow that standard, and I don't believe that `goto` is considered _harmful_ when used _properly_. In fact, there is a lot of code that is so nicely written with `goto` than were it written with if/else statements. The other day, I stumbled on [this article](https://blog.joren.ga/gotophobia-harmful) which includes some interesting links and nice uses of `goto`.

**Comment by LoupVaillant** [comment]
> Now, the `BAIL_IF(err, err)` construct, I actually have done it while playing with this idea, and find it kind of obscure (magical).

Of course :facepalm: I wasn't being consistent with myself here: I usually have a similar attitude towards most tests, where I like to give actual booleans to things that expect truth values (`if`, `while`, `assert`…):  `x != 0`, `ptr != NULL`. I should have applied the same policy to `err != ERR_OK`.

> To think about it: all our `BAIL`s follow a test actually. _But_! […]

That's… actually a very good point. I originally blindly thought about replacing 3 lines with 1. But that's not quite it. Side by side, we're really comparing the following:

```C
if (condition) { BAIL(ERROR_CODE); }
BAIL_IF(condition, ERROR_CODE);
```

And if we only highlight the difference:

```C
if () { BAIL(); }
BAIL_IF(, );
```

And that's if we insist on the curly brackets (I usually do). Without them we get:

```C
if () BAIL();
BAIL_IF(, );
```

That's saving like _one_ character, which looks so ridiculous compared to what I though we saved (2 whole lines of code). This was a case of me getting blinded by SLoC savings, and failing to look at the relevant syntactic elements.

`BAIL_IF_NOT_OK()` on the other hand does save some code:

```C
err = exp; if (err != ERR_OK) BAIL(err);
BAIL_IF_NOT_OK(exp);
```

**Comment by ewd340** [comment]
> And that's if we insist on the curly brackets (I usually do). Without them we get:
> ```c
> if () BAIL();
> BAIL_IF(, );
> ```

Haven't seen it that that way, Indeed. However, I, too, do insist on curly brackets (even for a single statement).

> `BAIL_IF_NOT_OK() ` on the other hand does save some code:
> 
> ```c
> err = exp; if (err != ERR_OK) BAIL(err);
> BAIL_IF_NOT_OK(exp);
> ```

True, but what I actually don't like about `BAIL_IF_NOT_OK` is that it _hides_ the fact that `exp` does have an effect (that it is _active_). Take for example:

```c
BAIL_IF_NOT_OK(write_keyfile(out, key));
```
It is short and nice, but has something not quite OK to it (that's how I see it): it kind of hides the fact that `write_keyfile(out, key)` has to be actually run (with side effects). It does not have the same _taste_ and _clarity_ as this one:

```c
err = write_keyfile(out, key)
BAIL_IF_NOT_OK(err);
```

Or even this one (if we don't care about SLoC):

```c
err = write_keyfile(out, key)
IF (err != ERR_OK) {
    BAIL(err):
}
```

**Comment by LoupVaillant** [comment]
I see. I don't think I disagree.

Well, those were my suggestions. I'm not even sure you should follow them. I already quite like your code anyway. And with this my review is done. Good work!

**Comment by ewd340** [comment]
I liked your review @LoupVaillant and I'm sincerely grateful that you took the time to launch and discuss these issues. Both this issue and   issue #3 actually bring some cool changes to `kr`.

This very issue generated a very creative exchange I really liked, and _also_ highlighted the fact that we can get rid of the _oxymoronic_ construct that is `BAIL(ERR_OK)`, 

As for issue #3, it brings a very-welcome generalization to keyfiles.

Again thank you!
